name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    env:
      AWS_REGION: ap-south-1
      CLUSTER_NAME: vikas-cluster
      NAMESPACE: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Account
        run: |
          aws sts get-caller-identity
          aws configure list

      - name: Verify EKS Cluster
        run: |
          echo "Available clusters:"
          aws eks list-clusters --region $AWS_REGION

          echo "Checking cluster..."
          aws eks describe-cluster \
            --name $CLUSTER_NAME \
            --region $AWS_REGION

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --name $CLUSTER_NAME \
            --region $AWS_REGION

          kubectl get nodes

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin
          skaffold version

      - name: Debug Skaffold File
        run: |
          echo "Current directory:"
          pwd

          echo ""
          echo "Files:"
          ls -la

          echo ""
          echo "skaffold.yaml:"
          cat skaffold.yaml

      - name: Create Namespace
        run: |
          kubectl create namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Create ECR Repositories
        shell: bash
        run: |
          ...

      - name: Create Namespace
        run: |
          kubectl create namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Create ECR Repositories
        shell: bash
        run: |
          REPOS=(
            adservice
            cartservice
            checkoutservice
            currencyservice
            emailservice
            frontend
            loadgenerator
            paymentservice
            productcatalogservice
            recommendationservice
            shippingservice
          )

          for repo in "${REPOS[@]}"; do

            REPO="online-boutique/$repo"

            echo "Processing $REPO"

            if aws ecr describe-repositories \
              --repository-names "$REPO" \
              --region "$AWS_REGION" >/dev/null 2>&1
            then
              echo "Repository exists."
            else
              echo "Creating repository..."

              aws ecr create-repository \
                --repository-name "$REPO" \
                --region "$AWS_REGION"
            fi

          done

      - name: Build and Deploy
        run: |
          skaffold config set --global local-cluster false

          skaffold run \
            --default-repo=${{ steps.login-ecr.outputs.registry }}/online-boutique \
            --tag=${{ github.sha }} \
            --namespace=$NAMESPACE

      - name: Wait for Deployments
        run: |
          kubectl wait deployment \
            --all \
            --for=condition=Available \
            --timeout=600s \
            -n $NAMESPACE

      - name: Deployment Status
        run: |
          echo "Pods"
          kubectl get pods -n $NAMESPACE

          echo ""
          echo "Services"
          kubectl get svc -n $NAMESPACE

          echo ""
          echo "Deployments"
          kubectl get deployment -n $NAMESPACE

          echo ""
          echo "Ingress"
          kubectl get ingress -n $NAMESPACE || true
